//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Management_System.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/clientLibrary")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clientC", Namespace="http://schemas.datacontract.org/2004/07/clientLibrary")]
    [System.SerializableAttribute()]
    public partial class clientC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalAddField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResidentialAddField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkAddField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string workNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalAdd {
            get {
                return this.PostalAddField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalAddField, value) != true)) {
                    this.PostalAddField = value;
                    this.RaisePropertyChanged("PostalAdd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResidentialAdd {
            get {
                return this.ResidentialAddField;
            }
            set {
                if ((object.ReferenceEquals(this.ResidentialAddField, value) != true)) {
                    this.ResidentialAddField = value;
                    this.RaisePropertyChanged("ResidentialAdd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkAdd {
            get {
                return this.WorkAddField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkAddField, value) != true)) {
                    this.WorkAddField = value;
                    this.RaisePropertyChanged("WorkAdd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.mobileNumberField, value) != true)) {
                    this.mobileNumberField = value;
                    this.RaisePropertyChanged("mobileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string workNumber {
            get {
                return this.workNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.workNumberField, value) != true)) {
                    this.workNumberField = value;
                    this.RaisePropertyChanged("workNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        Client_Management_System.ServiceReference1.CompositeType GetDataUsingDataContract(Client_Management_System.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Client_Management_System.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(Client_Management_System.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertClient", ReplyAction="http://tempuri.org/IService1/insertClientResponse")]
        int insertClient(Client_Management_System.ServiceReference1.clientC c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertClient", ReplyAction="http://tempuri.org/IService1/insertClientResponse")]
        System.Threading.Tasks.Task<int> insertClientAsync(Client_Management_System.ServiceReference1.clientC c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getClients", ReplyAction="http://tempuri.org/IService1/getClientsResponse")]
        Client_Management_System.ServiceReference1.clientC[] getClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getClients", ReplyAction="http://tempuri.org/IService1/getClientsResponse")]
        System.Threading.Tasks.Task<Client_Management_System.ServiceReference1.clientC[]> getClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateClient", ReplyAction="http://tempuri.org/IService1/updateClientResponse")]
        int updateClient(Client_Management_System.ServiceReference1.clientC c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateClient", ReplyAction="http://tempuri.org/IService1/updateClientResponse")]
        System.Threading.Tasks.Task<int> updateClientAsync(Client_Management_System.ServiceReference1.clientC c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteClient", ReplyAction="http://tempuri.org/IService1/deleteClientResponse")]
        int deleteClient(Client_Management_System.ServiceReference1.clientC c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteClient", ReplyAction="http://tempuri.org/IService1/deleteClientResponse")]
        System.Threading.Tasks.Task<int> deleteClientAsync(Client_Management_System.ServiceReference1.clientC c);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client_Management_System.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client_Management_System.ServiceReference1.IService1>, Client_Management_System.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Client_Management_System.ServiceReference1.CompositeType GetDataUsingDataContract(Client_Management_System.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Client_Management_System.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(Client_Management_System.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public int insertClient(Client_Management_System.ServiceReference1.clientC c) {
            return base.Channel.insertClient(c);
        }
        
        public System.Threading.Tasks.Task<int> insertClientAsync(Client_Management_System.ServiceReference1.clientC c) {
            return base.Channel.insertClientAsync(c);
        }
        
        public Client_Management_System.ServiceReference1.clientC[] getClients() {
            return base.Channel.getClients();
        }
        
        public System.Threading.Tasks.Task<Client_Management_System.ServiceReference1.clientC[]> getClientsAsync() {
            return base.Channel.getClientsAsync();
        }
        
        public int updateClient(Client_Management_System.ServiceReference1.clientC c) {
            return base.Channel.updateClient(c);
        }
        
        public System.Threading.Tasks.Task<int> updateClientAsync(Client_Management_System.ServiceReference1.clientC c) {
            return base.Channel.updateClientAsync(c);
        }
        
        public int deleteClient(Client_Management_System.ServiceReference1.clientC c) {
            return base.Channel.deleteClient(c);
        }
        
        public System.Threading.Tasks.Task<int> deleteClientAsync(Client_Management_System.ServiceReference1.clientC c) {
            return base.Channel.deleteClientAsync(c);
        }
    }
}
